name: deploy-ec2-on-push-event
run-name: ${{ github.actor }} 
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: import code to action
          uses: actions/checkout@v3
       
        
        