name: deploy-terraform-on-aws
run-name: terraform-aws-deploy-${{ github.actor }} 
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: import code to action
          uses: actions/checkout@v3
       
        - name: Set up AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1  

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.5.5
        
        - name: navigate to terraform files
          run: |
            cd ./terraform
            ls

        - name: Terraform init
          run: terraform init
    
        - name: Terraform apply
          run: terraform apply -auto-approve
    
        - name: Cleanup
          run: |
             terraform destroy -auto-approve 
             rm -rf .terraform
             cd ..
        