name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  schedule:
        - cron: "*/5 * * * *"
  push:
    branches:
      - main
    
jobs:
  build-test-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
         
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.16.x'
        
        - name: Build
          run: go build -o main_build go_log.go

        - name: Test the app
          run: go test go_log_test.go go_log.go
        