name: exersice-4-cond
run-name: ${{ github.actor }}
on:
  push:
    paths:
      - abc.txt
jobs:
  cond-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "there where changes to abc.txt"



