name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  my-simple-job:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the repo
          uses: actions/checkout@v3
        
        - name: Build
          run: go build -o main_build go_log.go

        - name: Test
          run: go test 
